# Generated by Django 4.1.4 on 2022-12-09 15:12

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='characters/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='comics/')),
                ('urls', models.ManyToManyField(blank=True, to='base.link')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None)),
                ('image', models.ImageField(blank=True, max_length=512, null=True, upload_to='locations/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comic.act')),
                ('comic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comic.comic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='act',
            name='comic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.comic'),
        ),
    ]
