# Generated by Django 4.1.4 on 2022-12-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comic.page'),
        ),
        migrations.AddField(
            model_name='media',
            name='urls',
            field=models.ManyToManyField(blank=True, to='base.link'),
        ),
        migrations.AddField(
            model_name='file',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.artist'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.artist'),
        ),
        migrations.AddField(
            model_name='artist',
            name='urls',
            field=models.ManyToManyField(blank=True, to='base.link'),
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.artist'),
        ),
        migrations.AddField(
            model_name='art',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='art_characters', to='comic.character'),
        ),
        migrations.AddField(
            model_name='art',
            name='commentary',
            field=models.ManyToManyField(blank=True, related_name='arts', to='base.commentary'),
        ),
        migrations.AddField(
            model_name='art',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='art_locations', to='comic.location'),
        ),
        migrations.AlterUniqueTogether(
            name='mediaartist',
            unique_together={('media', 'artist')},
        ),
    ]
